#!/bin/bash


module load CheckM/1.1.3-intel-2020a-Python-3.8.2

echo Start Job

date

echo CheckM on consensus genomes located in ./01_data_analysis/02_assembly/02_medaka_consensus

mkdir ./01_data_analysis/02_assembly/04_checkm
cd ./01_data_analysis/02_assembly/04_checkm

for dir in ./01_data_analysis/02_assembly/02_medaka_consensus/*/
do
   dirname=$(basename "$dir")
   echo $dirname
   checkm lineage_wf -t 32 -x fasta ./01_data_analysis/02_assembly/02_medaka_consensus/$dirname $dirname --pplacer_threads=32 --tab_table -f ./01_data_analysis/02_assembly/04_checkm/$dirname/${dirname}.log

done

date

echo End Job