#!/bin/bash

echo Start Job

date

echo Reordering draft genomes using Mauve against reference genome
#README: indicate the path to the reference genome in parameter -ref (line 20)

module load mauveAligner/4736-gompi-2020a

mkdir ./SA/01_data_analysis/03_reordered_genomes
cd ./SA/01_data_analysis/03_reordered_genomes

for genome in ./SA/00_data/03_genomes/*.fasta
do
   isolate=$(basename $genome .fasta)
   echo Reordering $isolate

   java -Xmx500m -cp /kyukon/home/gent/476/vsc47636/mauve_snapshot_2015-02-13/Mauve.jar org.gel.mauve.contigs.ContigOrderer -output $isolate -draft $genome -ref ./SA/01_data_analysis/NCTC8325.fasta

done



date

echo End Job