#!/bin/bash


echo Start Job

date


echo Annotating genomes using Prokka
#README: the annotations of a reference genome will be used as reference. Modify the parameter --proteins as desired or removed it

module load prokka/1.14.5-gompi-2020b

mkdir ./SA/01_data_analysis/04_annotation
cd ./SA/01_data_analysis/04_annotation

for genome in ./SA/00_data/03_reordered_genomes/*.fasta
do
   isolate=$(basename $genome .fasta)
   locustag="${isolate}_L"

   echo $genome

   prokka $genome --outdir $isolate --prefix $isolate --proteins ./SA/01_data_analysis/NCTC8325.gb --locustag $locustag --genus Staphylococcus --species aureus --strain $isolate --kingdom Bacteria --gcode 11 --usegenus --addgenes --rawproduct

done




date

echo End Job
