#!/bin/bash

echo Start Job

date

echo Searching for AMR genes using ABRicate and the databases Argannot, CARD, Megares, NCBI and Resfinder

module load ABRicate/0.9.9-gompi-2019b

mkdir ./SA/01_data_analysis/05_AMR_ABRicate
cd ./SA/01_data_analysis/05_AMR_ABRicate

for genome in ./SA/01_data_analysis/03_genomes/*.fasta
do
   isolate=$(basename $genome .fasta)
   echo Searching for AMR genes in isolate $isolate

   abricate $genome --db argannot --nopath > ./SA/01_data_analysis/05_AMR_ABRicate/${isolate}_argannot.tab

   abricate $genome --db card --nopath > ./SA/01_data_analysis/05_AMR_ABRicate/${isolate}_card.tab

   abricate $genome --db megares --nopath > ./SA/01_data_analysis/05_AMR_ABRicate/${isolate}_megares.tab

   abricate $genome --db ncbi --nopath > ./SA/01_data_analysis/05_AMR_ABRicate/${isolate}_ncbi.tab

   abricate $genome --db resfinder --nopath > ./SA/01_data_analysis/05_AMR_ABRicate/${isolate}_resfinder.tab

done


echo Concatenate the output for each isolate and database in one single file named abricate_output.tab

head -n 1 ./SA/01_data_analysis/05_AMR_ABRicate/* | tail -n +1 > ./SA/01_data_analysis/05_AMR_ABRicate/abricate_output.tab && tail -n +2 -q ./SA/01_data_analysis/05_AMR_ABRicate/* >> ./SA/01_data_analysis/05_AMR_ABRicate/abricate_output.tab



date

echo End Job
